"""simplify trials index

Revision ID: 704895440a03
Revises: baseline
Create Date: 2026-01-13 15:45:12.105044

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "704895440a03"
down_revision: Union[str, Sequence[str], None] = "baseline"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
