"""restore api_keys foreign keys after moving the model back into backend

API keys are a hosted/cloud feature; the ``APIKeyModel`` was moved back from the
core ``oddish`` package into ``backend/models.py``. With the model living
alongside ``organizations``/``users`` again, restore the DB-level FKs that
#414's ``apk01dropfk`` (oddish tree) targeted.

Idempotent: ``a1b2c3d4e5f6`` already creates the canonical ``fk_api_keys_*``
constraints, so on a migration-built DB this is a no-op. It only does real work
on databases where the autogenerated ``api_keys_*_fkey`` constraints were
dropped (e.g. a schema once built from the post-#414 metadata).

Revision ID: apkfk01restore
Revises: s5t6u7v8w9x0
Create Date: 2026-06-29
"""

from typing import Sequence, Union

from alembic import op


revision: str = "apkfk01restore"
down_revision: Union[str, Sequence[str], None] = "s5t6u7v8w9x0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Drop any stray autogenerated-name FKs first so we never end up with two
    # FKs on the same column, then (re)create the canonical named constraints.
    op.execute("ALTER TABLE api_keys DROP CONSTRAINT IF EXISTS api_keys_org_id_fkey")
    op.execute(
        "ALTER TABLE api_keys DROP CONSTRAINT IF EXISTS api_keys_created_by_user_id_fkey"
    )
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint WHERE conname = 'fk_api_keys_org_id'
            ) THEN
                ALTER TABLE api_keys
                ADD CONSTRAINT fk_api_keys_org_id
                FOREIGN KEY (org_id) REFERENCES organizations (id) ON DELETE CASCADE;
            END IF;
        END $$;
        """
    )
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint WHERE conname = 'fk_api_keys_created_by_user_id'
            ) THEN
                ALTER TABLE api_keys
                ADD CONSTRAINT fk_api_keys_created_by_user_id
                FOREIGN KEY (created_by_user_id) REFERENCES users (id) ON DELETE SET NULL;
            END IF;
        END $$;
        """
    )


def downgrade() -> None:
    op.execute(
        "ALTER TABLE api_keys DROP CONSTRAINT IF EXISTS fk_api_keys_created_by_user_id"
    )
    op.execute("ALTER TABLE api_keys DROP CONSTRAINT IF EXISTS fk_api_keys_org_id")
