from oddish.db.models import (
    AnalysisStatus,
    Base,
    JobStatus,
    Priority,
    QueueSlotModel,
    TaskStatus,
    TrialOrigin,
    TrialStatus,
    VerdictStatus,
    WorkerJobKind,
    WorkerJobStatus,
    TagState,
    TagVisibility,
    TagAssignmentScope,
    TagAssignmentState,
    TagAssignmentSource,
    TagGrantPrincipal,
    TagGrantCapability,
    TagEventAction,
    TagEventActor,
    TagEventSource,
    SavedTagFilterVisibility,
    TagPolicyWhoCanCreate,
    TagPolicyProfanityMode,
    # ORM Models
    DocumentModel,
    ExperimentModel,
    TagModel,
    TagAssignmentModel,
    TagExclusionModel,
    TagGrantModel,
    TagEventModel,
    TagPolicyModel,
    SavedTagFilterModel,
    SkillModel,
    SkillFileModel,
    TaskModel,
    TaskVersionModel,
    TrialModel,
    WorkerJobModel,
    task_experiments,
    # Helpers
    generate_id,
    utcnow,
)

# Connection
from oddish.db.connection import (
    close_database_connections,
    close_engine,
    close_pool,
    engine,
    get_pool,
    reconfigure_database_connections,
    get_session,
    drop_db,
    init_db,
    reset_db,
)

# Storage
from oddish.db.storage import (
    StorageClient,
    get_storage_client,
)

# Soft-delete helpers
from oddish.db.soft_delete import (
    INCLUDE_DELETED_OPTION,
    get_soft_delete_models,
    install_soft_delete_filter,
    register_soft_delete_models,
)

__all__ = [
    # Base
    "Base",
    # Enums
    "TaskStatus",
    "JobStatus",
    "TrialStatus",
    "TrialOrigin",
    "AnalysisStatus",
    "VerdictStatus",
    "Priority",
    "WorkerJobKind",
    "WorkerJobStatus",
    "TagState",
    "TagVisibility",
    "TagAssignmentScope",
    "TagAssignmentState",
    "TagAssignmentSource",
    "TagGrantPrincipal",
    "TagGrantCapability",
    "TagEventAction",
    "TagEventActor",
    "TagEventSource",
    "SavedTagFilterVisibility",
    "TagPolicyWhoCanCreate",
    "TagPolicyProfanityMode",
    # ORM Models
    "ExperimentModel",
    "DocumentModel",
    "SkillModel",
    "SkillFileModel",
    "QueueSlotModel",
    "TagModel",
    "TagAssignmentModel",
    "TagExclusionModel",
    "TagGrantModel",
    "TagEventModel",
    "TagPolicyModel",
    "SavedTagFilterModel",
    "TaskModel",
    "TaskVersionModel",
    "TrialModel",
    "WorkerJobModel",
    "task_experiments",
    # Helpers
    "generate_id",
    "utcnow",
    # Session/Pool
    "engine",
    "get_session",
    "get_pool",
    "close_pool",
    "close_engine",
    "close_database_connections",
    "reconfigure_database_connections",
    # Setup
    "init_db",
    "drop_db",
    "reset_db",
    # Storage
    "StorageClient",
    "get_storage_client",
    # Soft delete
    "INCLUDE_DELETED_OPTION",
    "get_soft_delete_models",
    "install_soft_delete_filter",
    "register_soft_delete_models",
]
